#!/usr/bin/env bash
set -euo pipefail

echo "=== Stage 6C Universal Intent Router route inventory smoke ==="

fail=0

mkdir -p docs/generated

doc6a="docs/stage-6a-universal-intent-router-foundation-plan.md"
doc6b="docs/stage-6b-universal-intent-router-input-surface-audit.md"
doc6c="docs/stage-6c-universal-intent-router-route-inventory.md"
inventory="docs/generated/stage-6c-route-inventory.txt"

echo
echo "=== required docs ==="
for f in "$doc6a" "$doc6b" "$doc6c"; do
  if [ -s "$f" ]; then
    echo "OK: $f"
  else
    echo "FAIL: missing or empty $f"
    fail=1
  fi
done

echo
echo "=== generate backend route inventory snapshot ==="
{
  echo "# Stage 6C Route Inventory Snapshot"
  echo
  echo "Generated by ops/smoke/check-stage-6c-universal-intent-router-route-inventory.sh"
  echo
  echo "## FastAPI routes in edge_controller.py"
  grep -nE '^@app\.(get|post|put|patch|delete)\(' edge_controller.py || true

  echo
  echo "## Public gateway routes if present"
  if [ -f public_gateway.py ]; then
    grep -nE '^@app\.(get|post|put|patch|delete)\(' public_gateway.py || true
  else
    echo "public_gateway.py not present"
  fi

  echo
  echo "## Frontend fetch calls"
  grep -RInE 'fetch\(|axios\.|XMLHttpRequest|sendBeacon' frontend public 2>/dev/null || true

  echo
  echo "## HTML form/input/button references"
  grep -RInE '<form|<input|<textarea|<button|contenteditable' frontend public 2>/dev/null || true
} > "$inventory"

if [ -s "$inventory" ]; then
  echo "OK: generated $inventory"
else
  echo "FAIL: inventory not generated"
  fail=1
fi

echo
echo "=== inventory quick counts ==="
backend_route_count="$(grep -c '^.*@app\.' "$inventory" || true)"
fetch_count="$(grep -cE 'fetch\(|axios\.|XMLHttpRequest|sendBeacon' "$inventory" || true)"
input_count="$(grep -cE '<form|<input|<textarea|<button|contenteditable' "$inventory" || true)"

echo "backend_route_count=$backend_route_count"
echo "fetch_count=$fetch_count"
echo "input_count=$input_count"

if [ "${backend_route_count:-0}" -lt 1 ]; then
  echo "FAIL: no backend routes found"
  fail=1
fi

echo
echo "=== required Stage 6C markers ==="
for marker in \
  "Route classes" \
  "Router candidate routes" \
  "Direct application routes" \
  "Internal service routes" \
  "Admin/system routes" \
  "Initial safety classes" \
  "Never direct-router-execute"
do
  if grep -q "$marker" "$doc6c"; then
    echo "OK: found marker: $marker"
  else
    echo "FAIL: missing marker: $marker"
    fail=1
  fi
done

echo
echo "=== runtime code should not be modified for this planning stage ==="
if git diff --name-only | grep -E '(^edge_controller.py$|^frontend/|^backend/|^public_gateway.py$|^ops/systemd/)' >/dev/null; then
  echo "FAIL: runtime or systemd files are modified:"
  git diff --name-only | grep -E '(^edge_controller.py$|^frontend/|^backend/|^public_gateway.py$|^ops/systemd/)' || true
  fail=1
else
  echo "OK: no runtime/systemd file modifications detected"
fi

echo
echo "=== generated inventory preview ==="
sed -n '1,180p' "$inventory"

echo
echo "=== git status ==="
git status --short

echo
if [ "$fail" -eq 0 ]; then
  echo "PASS: Stage 6C Universal Intent Router route inventory smoke passed"
else
  echo "FAIL: Stage 6C Universal Intent Router route inventory smoke failed"
fi

exit "$fail"
