#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(pwd)}"
cd "$ROOT"
INDEX="frontend/wrapper-ui/apc-wrapper-local/index.html"
CSS="frontend/wrapper-ui/apc-wrapper-local/privatepages/profile-accordion-input-polish.css"
JS="frontend/wrapper-ui/apc-wrapper-local/privatepages/profile-accordion-input-polish.js"

test -f "$INDEX"
test -f "$CSS"
test -f "$JS"
grep -q 'profile-accordion-input-polish.css' "$INDEX"
grep -q 'profile-accordion-input-polish.js' "$INDEX"
grep -q 'APC_PROFILE_ACCORDION_INPUT_POLISH_R16CG_R3' "$JS"
grep -q -- '-webkit-text-fill-color: #111827' "$CSS"
grep -q 'apc-profile-accordion-toggle' "$CSS"
grep -q 'Choose companion' "$JS"
grep -q 'Local backup folder' "$JS"
sha256sum "$INDEX" "$CSS" "$JS"
echo "PASS stage-17k-r16cg-r3-profile-accordion-input-text-fix-source-only smoke"
