#!/usr/bin/env bash
set -euo pipefail

DOC="docs/phase-14j-fh-website-edge-nginx-static-wrapper-local-runtime-apply.md"

echo "=== Phase 14J-FH smoke: website-edge nginx static wrapper local runtime apply record ==="

test -f "$DOC"

require_marker() {
  local marker="$1"
  if grep -Fq -- "$marker" "$DOC"; then
    echo "PASS: marker present: $marker"
  else
    echo "FAIL: marker missing: $marker" >&2
    exit 1
  fi
}

require_marker "PHASE_14J_FH_WEBSITE_EDGE_NGINX_STATIC_WRAPPER_LOCAL_RUNTIME_APPLY"
require_marker "Previous commit: cc74a88"
require_marker "sudo: interactive authentication is required"
require_marker "Successful FH retry"
require_marker "hostname=website-edge"
require_marker "os_version=26.04"
require_marker "PASS: nginx service active before FH"
require_marker "head_now=03a6b4e"
require_marker "tag_now=03a6b4e"
require_marker "git_status_short=<clean>"
require_marker "PASS: sparse checkout patterns match expected non-cone static paths"
require_marker "actual_worktree_file_count=18"
require_marker "PASS: actual filesystem worktree limited to frontend/wrapper-ui and frontend/study-ui"
require_marker "PASS: command absent before fh: docker"
require_marker "PASS: command absent before fh: cloudflared"
require_marker "PASS: command absent before fh: node"
require_marker "PASS: command absent before fh: npm"
require_marker "PASS: selected nginx local port has no listener before FH"
require_marker "PASS: source wrapper static file present: index.html"
require_marker "PASS: source wrapper static file present: app.js"
require_marker "PASS: source wrapper static file present: styles.css"
require_marker "PASS: source wrapper static file present: queued_chat_config.js"
require_marker "PASS: dev_server.py exists in source checkout but will not be copied to nginx docroot"
require_marker "PASS: staged docroot excludes Python/runtime files"
require_marker "PASS: staged docroot has no obvious secret/key/env filenames"
require_marker "PASS: nginx docroot populated with wrapper static files only"
require_marker "PASS: nginx docroot excludes Python/runtime files"
require_marker "PASS: nginx docroot has no obvious secret/key/env filenames"
require_marker "PASS: copied file hash matches source: index.html"
require_marker "PASS: copied file hash matches source: app.js"
require_marker "PASS: copied file hash matches source: styles.css"
require_marker "PASS: copied file hash matches source: queued_chat_config.js"
require_marker "PASS: nginx local static site config written and enabled"
require_marker "PASS: nginx config test passed before reload"
require_marker "PASS: nginx reload succeeded after config test"
require_marker "PASS: nginx listener is bound to loopback on local port"
require_marker "PASS: no wildcard/non-loopback nginx listener detected for local port"
require_marker "nginx_local_get_root_index_html_status=200"
require_marker "PASS: nginx local GET / matches wrapper index.html"
require_marker "nginx_local_get_app_js_status=200"
require_marker "PASS: nginx local GET /app.js matches wrapper app.js"
require_marker "nginx_local_get_styles_css_status=200"
require_marker "PASS: nginx local GET /styles.css matches wrapper styles.css"
require_marker "nginx_local_get_queued_chat_config_js_status=200"
require_marker "PASS: nginx local GET /queued_chat_config.js matches wrapper queued_chat_config.js"
require_marker "PASS: source checkout remains clean after FH"
require_marker "PASS: final nginx config test passed"
require_marker "cloudflare_test_route_performed=no"
require_marker "cloudflare_production_cutover_performed=no"
require_marker "cloudflared_install_performed=no"
require_marker "docker_install_performed=no"
require_marker "node_npm_install_performed=no"
require_marker "app_systemd_runtime_creation_performed=no"
require_marker "controller_queue_migration_performed=no"
require_marker "worker_start_performed=no"
require_marker "runtime_activation_limited_to_nginx_static_wrapper_local=yes"
require_marker "production_db_job_mutation_performed=no"
require_marker "ct101_call_performed=no"
require_marker "model_ollama_endpoint_call_performed=no"
require_marker "tailscale_acl_grants_tag_mutation_performed=no"
require_marker "tailscale_ssh_mode_enablement_performed=no"
require_marker "phase_14j_ag_apply_wrapper_rerun_performed=no"
require_marker "PHASE_14J_FH_RESULT=passed"
require_marker "nginx_static_wrapper_local_runtime_apply=passed"
require_marker "rollback_performed=no"
require_marker "phase_exit_code=0"
require_marker "PHASE_14J_FH_RESULT=website_edge_nginx_static_wrapper_local_runtime_apply_recorded"
require_marker "NEXT_SAFE_PHASE=plan_cloudflare_test_route_for_website_edge_nginx_local_runtime_without_production_cutover"

echo "PASS: Phase 14J-FH nginx static wrapper local runtime apply record is complete"
