#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3v-h-dry-run-wrapper-implementation-plan-no-apply.md"

echo "=== Stage 16 E3V-H smoke: dry-run wrapper implementation plan, no apply ==="

test -s "$DOC"

grep -F "No Apply" "$DOC" || grep -F "no-apply plan" "$DOC"
grep -F "does not implement the wrapper" "$DOC"
grep -F "does not execute the wrapper" "$DOC"
grep -F "does not write the DB" "$DOC"
grep -F "does not call a model" "$DOC"
grep -F "HEAD/origin/main: 09bd140" "$DOC"
grep -F "CT203 DB stat was unchanged" "$DOC"
grep -F -- "--dry-run: real read-only guard checks" "$DOC"
grep -F -- "--execute-approved: still refused" "$DOC"
grep -F "NO_DB_WRITE" "$DOC"
grep -F "NO_DB_CLAIM" "$DOC"
grep -F "NO_ADAPTER_CALL" "$DOC"
grep -F "NO_MODEL_CALL" "$DOC"
grep -F "E3V_OPTION_B_DRY_RUN_GUARD_PREFLIGHT_OK" "$DOC"
grep -F "E3V_DRY_RUN_RESULT=NO_ELIGIBLE_JOB_NO_RUNTIME" "$DOC"
grep -F "WOULD_ATOMIC_CLAIM job_id=<id>" "$DOC"
grep -F "REFUSE_MULTIPLE_ELIGIBLE_JOBS" "$DOC"
grep -F "qwen2.5:32b-instruct-q4_K_M" "$DOC"
grep -F "Forbidden job ids" "$DOC"
grep -F "23" "$DOC"
grep -F "24" "$DOC"
grep -F "27" "$DOC"
grep -F "28" "$DOC"
grep -F "no hardcoded pveso DNS dependency" "$DOC"
grep -F "non-localhost 11434 listener count is 0" "$DOC"
grep -F "CT101_STATUS=stopped" "$DOC"
grep -F "CT101_ONBOOT=0" "$DOC"
grep -F "DB_OPEN_MODE=sqlite_uri_mode_ro_immutable" "$DOC"
grep -F "DB_INTEGRITY=ok" "$DOC"
grep -F "DUPLICATE_JOB_RESULTS none" "$DOC"
grep -F "REFUSE_E3V_EXECUTE_NOT_ENABLED" "$DOC"
grep -F "E3V-I implement dry-run-only wrapper guard path" "$DOC"
grep -F "E3V-P explicitly approved one-job Option B atomic claim dispatch" "$DOC"
grep -F "runtime apply blocked" "$DOC"

echo "E3V_H_DRY_RUN_WRAPPER_IMPLEMENTATION_PLAN_NO_APPLY_SMOKE_OK"
