#!/usr/bin/env bash
set -euo pipefail

DOC="docs/phase-14j-fn-r8-website-edge-minimal-cloudflared-service-temp-hostname.md"

echo "=== Phase 14J-FN-R8 smoke: website-edge minimal cloudflared service temp hostname record ==="

test -f "$DOC"

require_marker() {
  local marker="$1"
  if grep -Fq -- "$marker" "$DOC"; then
    echo "PASS: marker present: $marker"
  else
    echo "FAIL: marker missing: $marker" >&2
    exit 1
  fi
}

require_marker "PHASE_14J_FN_R8_WEBSITE_EDGE_MINIMAL_CLOUDFLARED_SERVICE_TEMP_HOSTNAME"
require_marker "Previous commit: 4c781e6"
require_marker "MUTATION_SCOPE=website_edge_vm_200_minimal_cloudflared_service_setup_temp_hostname_only"
require_marker "PHASE_14J_FN_R8_RESULT=passed"
require_marker "minimal_cloudflared_service_setup_temp_hostname=passed"
require_marker "rollback_performed=no"
require_marker "temporary_test_hostname=website-edge-test.alexhartel.com"
require_marker "cloudflared_path=/usr/local/bin/cloudflared"
require_marker "cloudflared_version=cloudflared version 2026.6.0"
require_marker "cloudflared_service_file=/etc/systemd/system/cloudflared.service"
require_marker "cloudflared_service_file_mode=644"
require_marker "cloudflared_service_file_owner=root:root"
require_marker "cloudflared_service_file_content_printed=no"
require_marker "cloudflared_execstart_printed=no"
require_marker "cloudflared_service_uses_no_autoupdate=yes"
require_marker "cloudflared_service_uses_environment_file=yes"
require_marker "cloudflared_token_env_file=/etc/cloudflared/website-edge-tunnel.env"
require_marker "cloudflared_token_env_file_mode=600"
require_marker "cloudflared_token_env_file_owner=root:root"
require_marker "cloudflared_token_env_file_content_printed=no"
require_marker "cloudflared_load_state=loaded"
require_marker "cloudflared_active_state=active"
require_marker "cloudflared_sub_state=running"
require_marker "cloudflared_unit_file_state=enabled"
require_marker "cloudflared_service_status_sanitized=yes"
require_marker "cloudflared_update_service_created=no"
require_marker "cloudflared_update_timer_created=no"
require_marker "token_printed=no"
require_marker "token_in_apc_last_output=no"
require_marker "token_in_chatgpt=no"
require_marker "token_committed=no"
require_marker "token_in_source_files=no"
require_marker "nginx_config_test_before_fn_r8=passed"
require_marker "nginx_config_test_after_fn_r8=passed"
require_marker "pre_fn_r8_root_index_html_status=200"
require_marker "pre_fn_r8_app_js_status=200"
require_marker "pre_fn_r8_styles_css_status=200"
require_marker "pre_fn_r8_queued_chat_config_js_status=200"
require_marker "post_fn_r8_root_index_html_status=200"
require_marker "post_fn_r8_app_js_status=200"
require_marker "post_fn_r8_styles_css_status=200"
require_marker "post_fn_r8_queued_chat_config_js_status=200"
require_marker "public_fn_r8_root_index_html_status=200"
require_marker "public_fn_r8_root_marker_validation_passed=yes"
require_marker "public_fn_r8_app_js_status=200"
require_marker "public_fn_r8_styles_css_status=200"
require_marker "public_fn_r8_queued_chat_config_js_status=200"
require_marker "temporary_public_hostname_smoke_performed=yes"
require_marker "temporary_public_hostname_smoke_passed=yes"
require_marker "root_exact_hash_required=no"
require_marker "root_marker_validation_required=yes"
require_marker "asset_exact_hash_validation_required=yes"
require_marker "cloudflare_route_mutation_by_terminal_performed=no"
require_marker "cloudflare_production_cutover_performed=no"
require_marker "apex_root_route_replacement_performed=no"
require_marker "primary_public_route_replacement_performed=no"
require_marker "proxmox_public_exposure_performed=no"
require_marker "nginx_config_mutation_performed=no"
require_marker "docker_install_performed=no"
require_marker "node_npm_install_performed=no"
require_marker "tailscale_acl_grants_tag_mutation_performed=no"
require_marker "tailscale_ssh_mode_enablement_performed=no"
require_marker "subnet_routes_created=no"
require_marker "exit_node_enabled=no"
require_marker "controller_queue_migration_performed=no"
require_marker "worker_start_performed=no"
require_marker "production_db_job_mutation_performed=no"
require_marker "ct101_call_performed=no"
require_marker "model_ollama_endpoint_call_performed=no"
require_marker "phase_14j_ag_apply_wrapper_rerun_performed=no"
require_marker "PRODUCTION_CUTOVER_STATUS=not_performed"
require_marker "APEX_ROOT_ROUTE_REPLACEMENT_STATUS=not_performed"
require_marker "PRIMARY_PUBLIC_ROUTE_REPLACEMENT_STATUS=not_performed"
require_marker "TEMPORARY_TEST_HOSTNAME_ONLY=yes"
require_marker "NEXT_SAFE_PHASE=record_and_verify_fn_r8_then_plan_production_cutover_only_without_applying_cutover"

echo "PASS: Phase 14J-FN-R8 website-edge minimal cloudflared service temp hostname record is complete"
