#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-17k-r14j-r2-record-visible-status-preview-clean-ok-proof.md"
OUT_DIR="docs/smoke/generated/stage-17k-r14j-r2-record-visible-status-preview-clean-ok-proof"

test -f "$DOC"
test -d "$OUT_DIR"

grep -Fq "Record Visible Status Preview Clean-OK Proof" "$DOC"
grep -Fq "Recovery note" "$DOC"
grep -Fq "OUT_head" "$DOC"
grep -Fq "Browser proof passed" "$DOC"
grep -Fq "PASS_R14I_R2_VISIBLE_SAVE_ACTION_STATUS_NO_BUTTON_NO_WRITE_CLEAN_OK" "$DOC"
grep -Fq "Strict proof mismatch note" "$DOC"
grep -Fq "Legacy backend cache fields removed: 0" "$DOC"
grep -Fq "After legacy backend cache fields: none" "$DOC"
grep -Fq "removedCount 0" "$DOC"
grep -Fq "alreadyCleanOrSanitized true" "$DOC"
grep -Fq "afterLegacyFieldsNone true" "$DOC"
grep -Fq "controllerWindowPresent true" "$DOC"
grep -Fq "executorWindowPresent true" "$DOC"
grep -Fq "APC_PROFILE_LOCAL_BACKUPS_SAVE_ACTION_STATUS_PREVIEW_R14I_R2" "$DOC"
grep -Fq "hasUnsafeButton false" "$DOC"
grep -Fq "Button added: false" "$DOC"
grep -Fq "Click handler added: false" "$DOC"
grep -Fq "Current-file save enabled: false" "$DOC"
grep -Fq "Same-file write enabled: false" "$DOC"
grep -Fq "Executor call from UI allowed: false" "$DOC"
grep -Fq "Can write now: false" "$DOC"
grep -Fq "Writes enabled now: false" "$DOC"
grep -Fq "Executor called: false" "$DOC"
grep -Fq "buddies-who-study-current.json" "$DOC"
grep -Fq "buddies-who-study-current.previous.json" "$DOC"
grep -Fq "No Save button was added in this stage" "$DOC"
grep -Fq "No Profile click handler calls the write executor" "$DOC"
grep -Fq "No source mutation" "$DOC"
grep -Fq "No current-file save in live UI" "$DOC"
grep -Fq "No same-file write path in live UI" "$DOC"

echo "PASS stage-17k-r14j-r2 record visible status preview clean-ok proof smoke"
