#!/usr/bin/env bash
set -euo pipefail

PHASE="phase-14j-ez-record-website-vm-access-and-post-install-baseline"
DOC="docs/${PHASE}.md"

echo "=== Phase 14J-EZ smoke: record website VM access and post-install baseline ==="

test -f "$DOC"
echo "PASS: EZ doc exists"

for marker in \
  "PHASE_14J_EZ_RECORD_WEBSITE_VM_ACCESS_AND_POST_INSTALL_BASELINE" \
  "MUTATION_SCOPE=docs_smoke_only_record_vm_access_and_post_install_baseline" \
  "SAFE_TRAP_PATTERN=yes" \
  "NO_TRAP_EXIT=yes" \
  "PHASE_14J_EY_RESULT=website_vm_os_installed_and_login_screen_confirmed" \
  "PHASE_14J_EY_R_REINSTALL_RECOVERY_OCCURRED=yes" \
  "WEBSITE_VM_CLEAN_REINSTALL_COMPLETED=yes" \
  "WEBSITE_VM_LOGIN_AFTER_REINSTALL_SUCCESSFUL=yes" \
  "WEBSITE_VM_TAILSCALE_INSTALLED=yes" \
  "WEBSITE_VM_TAILSCALE_AUTHENTICATED=yes" \
  "WEBSITE_VM_TAILSCALE_ACCESS_SUCCESSFUL=yes" \
  "WEBSITE_VM_OPENSSH_SERVER_INSTALLED=yes" \
  "WEBSITE_VM_SSH_ACCESS_SUCCESSFUL=yes" \
  "WEBSITE_VM_SSH_PASSWORD_AUTH_REPAIRED=yes" \
  "WEBSITE_VM_TAILSCALE_SSH_MODE_ENABLED=no" \
  "WEBSITE_VM_TAILSCALE_ACL_GRANTS_TAG_MUTATION_PERFORMED=no" \
  "WEBSITE_VM_WRONG_TAILSCALE_IP_DEBUG_RESOLVED=yes" \
  "WEBSITE_VM_POST_INSTALL_BASELINE_RESULT=completed_read_only" \
  "RUN_LOCATION=inside_website_edge_vm_200_over_ssh" \
  "WEBSITE_VM_OS_ID=ubuntu" \
  "WEBSITE_VM_OS_VERSION_ID=26.04" \
  "WEBSITE_VM_KERNEL=7.0.0-22-generic" \
  "WEBSITE_VM_ARCH=x86_64" \
  "WEBSITE_VM_CPU_THREADS=2" \
  "WEBSITE_VM_MEM_TOTAL_MIB=1642" \
  "WEBSITE_VM_ROOT_AVAILABLE_MIB=13345" \
  "WEBSITE_VM_DISK_1_SIZE=20G" \
  "WEBSITE_VM_DEFAULT_ROUTE_PRESENT=yes" \
  "WEBSITE_VM_CONNECTIVITY_PING_PUBLIC_IP_RC=0" \
  "WEBSITE_VM_CONNECTIVITY_HTTPS_EXAMPLE_RC=0" \
  "WEBSITE_VM_CMD_GIT_PRESENT=yes" \
  "WEBSITE_VM_CMD_CURL_PRESENT=yes" \
  "WEBSITE_VM_CMD_JQ_PRESENT=yes" \
  "WEBSITE_VM_CMD_PYTHON3_PRESENT=yes" \
  "WEBSITE_VM_CMD_PYTHON3_VENV_PRESENT=no" \
  "WEBSITE_VM_CMD_NODE_PRESENT=no" \
  "WEBSITE_VM_CMD_NGINX_PRESENT=no" \
  "WEBSITE_VM_CMD_TAILSCALE_PRESENT=yes" \
  "WEBSITE_VM_SERVICE_SSH_ACTIVE=active" \
  "WEBSITE_VM_SERVICE_TAILSCALED_ACTIVE=active" \
  "WEBSITE_VM_UFW_ACTIVE=yes" \
  "GIT_CLONE_PERFORMED=no" \
  "APP_DEPLOYMENT_PERFORMED=no" \
  "CLOUDFLARE_CUTOVER_PERFORMED=no" \
  "TAILSCALE_ACL_GRANTS_TAG_MUTATION_PERFORMED=no" \
  "TAILSCALE_SSH_MODE_ENABLEMENT_PERFORMED=no" \
  "CONTROLLER_QUEUE_MIGRATION_PERFORMED=no" \
  "WORKER_START_PERFORMED=no" \
  "RUNTIME_ACTIVATION_PERFORMED=no" \
  "PRODUCTION_DB_JOB_MUTATION_PERFORMED=no" \
  "CT101_CALL_PERFORMED=no" \
  "MODEL_OLLAMA_ENDPOINT_CALL_PERFORMED=no" \
  "DO_NOT_RERUN_14J_AG_APPLY_WRAPPER=preserved" \
  "REQUIRE_PLAN_MINIMAL_WEBSITE_RUNTIME_BEFORE_INSTALL=yes" \
  "PHASE_14J_EZ_RESULT=website_vm_reinstall_access_bootstrap_and_post_install_baseline_recorded" \
  "NEXT_SAFE_PHASE=plan_minimal_website_runtime_on_website_edge"; do
  grep -F "$marker" "$DOC" >/dev/null
  echo "PASS: marker found: $marker"
done

echo "PASS: Phase 14J-EZ access/bootstrap/baseline record smoke passed"
