#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3x-f-final-small-model-runtime-proof-closure-read-only.md"

echo "=== Stage 16 E3X-F smoke: final small-model runtime proof closure read-only ==="

test -s "$DOC"

grep -F "Final Small-Model Runtime Proof Closure, Read-Only" "$DOC"
grep -F "E3X_F_FINAL_SMALL_MODEL_RUNTIME_PROOF_CLOSURE_READ_ONLY_OK" "$DOC"
grep -F "HEAD/origin/main/remote: e25cb71" "$DOC"
grep -F "job_id=31" "$DOC"
grep -F "status=completed" "$DOC"
grep -F "attempts=1" "$DOC"
grep -F "requested_model=qwen2.5:0.5b" "$DOC"
grep -F "job_type=stage16_e3x_small_model_timeout_safe_completion_smoke" "$DOC"
grep -F "result_rows=1" "$DOC"
grep -F "classification=completed_with_one_result" "$DOC"
grep -F "queued job -> atomic claim -> bounded PVESO Ollama call -> completion transaction -> one job_results row" "$DOC"
grep -F "job 29: failed, attempts=1, result_rows=0" "$DOC"
grep -F "job 30: failed, attempts=1, result_rows=0" "$DOC"
grep -F "DB_INTEGRITY=ok" "$DOC"
grep -F "JOBS_TOTAL=30" "$DOC"
grep -F "JOB_RESULTS_TOTAL=11" "$DOC"
grep -F "DUPLICATE_JOB_RESULTS none" "$DOC"
grep -F "E3X_F_RUNNING_E3V_E3W_E3X_JOB_COUNT=0" "$DOC"
grep -F "E3X_F_QUEUED_E3V_E3W_E3X_JOB_COUNT=0" "$DOC"
grep -F "E3X_F_DB_CLOSURE_OK" "$DOC"
grep -F "OLLAMA_SERVICE_STATE=active" "$DOC"
grep -F "OLLAMA_NONLOCALHOST_11434_LISTENER_COUNT=0" "$DOC"
grep -F "PVESO_ACTIVE_MODEL_CLIENT_COUNT=0" "$DOC"
grep -F "CT101_STATUS=stopped" "$DOC"
grep -F "CT101_ONBOOT=0" "$DOC"
grep -F "E3X_F_SMALL_MODEL_VISIBLE_TO_HOST_OLLAMA=true" "$DOC"
grep -F "E3X_F_PVESO_CLOSURE_OK" "$DOC"
grep -F "E3X-F did not:" "$DOC"
grep -F "call a model" "$DOC"
grep -F "activate scheduler" "$DOC"
grep -F "E3Y-A — scheduler integration readiness plan, no activation" "$DOC"
grep -F "Do not rerun E3V-Q" "$DOC"
grep -F "Do not retry job 29" "$DOC"
grep -F "Do not rerun job 30" "$DOC"
grep -F "Do not rerun job 31 without a new explicit plan and approval" "$DOC"

echo "E3X_F_FINAL_SMALL_MODEL_RUNTIME_PROOF_CLOSURE_READ_ONLY_SMOKE_OK"
