#!/usr/bin/env bash
set -euo pipefail
DOC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/docs/stage-17k-u-companion-anki-consented-study-handoff-plan.md"
test -f "$DOC"
grep -Fq 'Stage 17K-U-R2' "$DOC"
grep -Fq 'Companion Anki Consented Study Handoff Plan Repair' "$DOC"
grep -Fq 'single-line escaped-newline file' "$DOC"
grep -Fq 'shape-only' "$DOC"
grep -Fq 'explicit user consent' "$DOC"
grep -Fq 'current browser page/session only' "$DOC"
grep -Fq 'no Anki card text in localStorage' "$DOC"
grep -Fq 'no backend handoff until separately approved' "$DOC"
grep -Fq 'no model handoff until separately approved' "$DOC"
grep -Fq 'no Anki writes' "$DOC"
grep -Fq 'no Anki-to-MyDecks writeback' "$DOC"
grep -Fq 'consentedCurrentAnkiCardForStudyCommand' "$DOC"
grep -Fq 'consented: false' "$DOC"
grep -Fq 'consented: true' "$DOC"
grep -Fq 'No source runtime behavior is changed by this repair' "$DOC"
grep -Fq 'No backend deploy, DB write, Anki write' "$DOC"
grep -Fq 'No Anki question text or answer text is saved to repo docs' "$DOC"
line_count="$(wc -l < "$DOC")"
test "$line_count" -gt 50
echo "PASS: Stage 17K-U-R2 consented study handoff plan repair smoke passed"
