#!/usr/bin/env bash
set -euo pipefail

DOC="docs/phase-14j-fm-plan-token-safe-website-edge-tunnel-setup-temporary-test-hostname.md"

echo "=== Phase 14J-FM smoke: token-safe website-edge tunnel setup plan ==="

test -f "$DOC"

require_marker() {
  local marker="$1"
  if grep -Fq -- "$marker" "$DOC"; then
    echo "PASS: marker present: $marker"
  else
    echo "FAIL: marker missing: $marker" >&2
    exit 1
  fi
}

require_marker "PHASE_14J_FM_PLAN_TOKEN_SAFE_WEBSITE_EDGE_TUNNEL_SETUP_TEMPORARY_TEST_HOSTNAME"
require_marker "Previous commit: 66e4c4b"
require_marker "MUTATION_SCOPE=docs_smoke_only_token_safe_tunnel_setup_plan"
require_marker "WEBSITE_EDGE_CLOUDFLARED_INSTALL_ONLY_PASSED=yes"
require_marker "WEBSITE_EDGE_CLOUDFLARED_PATH=/usr/local/bin/cloudflared"
require_marker "WEBSITE_EDGE_CLOUDFLARED_VERSION=2026.6.0"
require_marker "WEBSITE_EDGE_CLOUDFLARED_SYSTEMD_UNIT_CREATED_OR_ENABLED=no"
require_marker "WEBSITE_EDGE_CLOUDFLARED_PROCESS_RUNNING_AFTER_INSTALL=no"
require_marker "WEBSITE_EDGE_CLOUDFLARE_TOKEN_USED=no"
require_marker "WEBSITE_EDGE_CLOUDFLARE_TUNNEL_AUTHENTICATED=no"
require_marker "WEBSITE_EDGE_CLOUDFLARE_ROUTE_MUTATION_PERFORMED=no"
require_marker "WEBSITE_EDGE_CLOUDFLARE_TEST_HOSTNAME_CREATED=no"
require_marker "WEBSITE_EDGE_CLOUDFLARE_PRODUCTION_CUTOVER_PERFORMED=no"
require_marker "WEBSITE_EDGE_NGINX_LOCAL_RUNTIME_HEALTHY_AFTER_FL=yes"
require_marker "WEBSITE_EDGE_NGINX_LOCAL_PORT=18080"
require_marker "TUNNEL_SETUP_DECISION=cloudflare_dashboard_managed_tunnel_token_to_website_edge_cloudflared"
require_marker "TUNNEL_ORIGIN_SERVICE=http_127_0_0_1_18080"
require_marker "TUNNEL_HOSTNAME_SCOPE=temporary_test_hostname_only"
require_marker "TUNNEL_PRODUCTION_SCOPE=no_apex_cutover_no_primary_route_replacement"
require_marker "CREDENTIAL_TYPE=dedicated_cloudflare_tunnel_token"
require_marker "GLOBAL_API_KEY_ALLOWED=no"
require_marker "BROAD_ACCOUNT_TOKEN_ALLOWED=no"
require_marker "DEDICATED_TUNNEL_TOKEN_ALLOWED=yes"
require_marker "TOKEN_PRINTING_ALLOWED=no"
require_marker "TOKEN_COMMIT_ALLOWED=no"
require_marker "TOKEN_SOURCE_FILE_ALLOWED=no"
require_marker "TOKEN_APC_LAST_OUTPUT_ALLOWED=no"
require_marker "TOKEN_CHATGPT_PASTE_ALLOWED=no"
require_marker "TOKEN_INTERACTIVE_HIDDEN_ENTRY_REQUIRED=yes"
require_marker "FUTURE_FN_ALLOWED_WEBSITE_EDGE_ONLY=yes"
require_marker "FUTURE_FN_ALLOWED_USE_EXISTING_CLOUDFLARED_BINARY=yes"
require_marker "FUTURE_FN_ALLOWED_DEDICATED_TUNNEL_TOKEN_ONLY=yes"
require_marker "FUTURE_FN_ALLOWED_INTERACTIVE_HIDDEN_TOKEN_ENTRY_ONLY=yes"
require_marker "FUTURE_FN_ALLOWED_CREATE_CLOUDFLARED_SERVICE=yes"
require_marker "FUTURE_FN_ALLOWED_START_CLOUDFLARED_SERVICE=yes"
require_marker "FUTURE_FN_ALLOWED_ORIGIN_127_0_0_1_18080=yes"
require_marker "FUTURE_FN_ALLOWED_TEMPORARY_TEST_HOSTNAME_ONLY=yes"
require_marker "FUTURE_FN_ALLOWED_ROLLBACK_DISABLE_SERVICE=yes"
require_marker "FUTURE_FN_DENY_TOKEN_PRINTING=yes"
require_marker "FUTURE_FN_DENY_TOKEN_IN_APC_LAST_OUTPUT=yes"
require_marker "FUTURE_FN_DENY_TOKEN_IN_CHATGPT=yes"
require_marker "FUTURE_FN_DENY_GLOBAL_CLOUDFLARE_API_KEY=yes"
require_marker "FUTURE_FN_DENY_BROAD_ACCOUNT_TOKEN=yes"
require_marker "FUTURE_FN_DENY_APEX_PRODUCTION_CUTOVER=yes"
require_marker "FUTURE_FN_DENY_PRIMARY_PUBLIC_ROUTE_REPLACEMENT=yes"
require_marker "FUTURE_FN_DENY_PROXMOX_PUBLIC_EXPOSURE=yes"
require_marker "FUTURE_FN_DENY_NGINX_CONFIG_MUTATION=yes"
require_marker "FUTURE_FN_DENY_DOCKER_INSTALL=yes"
require_marker "FUTURE_FN_DENY_NODE_NPM_INSTALL=yes"
require_marker "FUTURE_FN_DENY_CONTROLLER_QUEUE_MIGRATION=yes"
require_marker "FUTURE_FN_DENY_WORKER_START=yes"
require_marker "FUTURE_FN_DENY_RUNTIME_ACTIVATION_EXCEPT_STATIC_TUNNEL=yes"
require_marker "FUTURE_FN_DENY_PRODUCTION_DB_JOB_MUTATION=yes"
require_marker "FUTURE_FN_DENY_CT101_CALL=yes"
require_marker "FUTURE_FN_DENY_MODEL_OLLAMA_ENDPOINT_CALL=yes"
require_marker "FUTURE_FN_DENY_TAILSCALE_ACL_GRANTS_TAG_MUTATION=yes"
require_marker "FUTURE_FN_DENY_TAILSCALE_SSH_MODE_ENABLEMENT=yes"
require_marker "FUTURE_FN_DENY_SUBNET_ROUTES=yes"
require_marker "FUTURE_FN_DENY_EXIT_NODE=yes"
require_marker "FUTURE_FN_DENY_SECRETS_RAW_IPS_AUTH_URLS=yes"
require_marker "FUTURE_FN_DENY_14J_AG_APPLY_WRAPPER_RERUN=yes"
require_marker "ROLLBACK_FN_REQUIRED=yes"
require_marker "ROLLBACK_FN_DISABLE_CLOUDFLARED_SERVICE=yes"
require_marker "ROLLBACK_FN_DO_NOT_TOUCH_PRODUCTION_APEX_ROUTE=yes"
require_marker "PHASE_14J_FM_RESULT=token_safe_website_edge_tunnel_setup_plan_recorded"
require_marker "NEXT_SAFE_PHASE=approve_website_edge_cloudflared_token_service_setup_for_temporary_test_hostname_without_production_cutover"

echo "PASS: Phase 14J-FM token-safe website-edge tunnel setup plan is complete"
