#!/usr/bin/env bash
set -euo pipefail
DOC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/docs/stage-17k-t-companion-anki-active-session-controls-live-proof.md"
test -f "$DOC"
grep -Fq 'Stage 17K-T' "$DOC"
grep -Fq 'f0e23fe' "$DOC"
grep -Fq 'stage17kt-companion-anki-active-session-controls-20260628' "$DOC"
grep -Fq 'mounted: true' "$DOC"
grep -Fq 'controlsVisible: true' "$DOC"
grep -Fq 'fileInputVisible: true' "$DOC"
grep -Fq 'sessionStatus: active' "$DOC"
grep -Fq 'active: true' "$DOC"
grep -Fq 'selectedDeckName: Anki Deck1' "$DOC"
grep -Fq 'cardCountInMemory: 2' "$DOC"
grep -Fq 'shape.present: true' "$DOC"
grep -Fq 'shape.has_question: true' "$DOC"
grep -Fq 'shape.has_answer: true' "$DOC"
grep -Fq 'doesNotReturnQuestionText: true' "$DOC"
grep -Fq 'doesNotReturnAnswerText: true' "$DOC"
grep -Fq 'noBackendAllowed: true' "$DOC"
grep -Fq 'noModelAllowed: true' "$DOC"
grep -Fq 'noAnkiWriteAllowed: true' "$DOC"
grep -Fq 'No Anki question text or answer text was saved to repo docs' "$DOC"
echo "PASS: Stage 17K-T live proof smoke passed"
