#!/usr/bin/env bash
set -euo pipefail
DOC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/docs/stage-17k-s-r3-anki-readonly-renderpanel-export-live-proof.md"
test -f "$DOC"
grep -Fq 'Stage 17K-S-R3' "$DOC"
grep -Fq 'a859316' "$DOC"
grep -Fq 'stage17ks-r3-anki-readonly-renderpanel-export-20260628' "$DOC"
grep -Fq 'stage17ks-r2-companion-local-anki-session-mount-output-repair-20260628' "$DOC"
grep -Fq 'adapterHasRenderPanel: true' "$DOC"
grep -Fq 'command: mount_anki_session_adapter' "$DOC"
grep -Fq 'mounted: true' "$DOC"
grep -Fq 'panelHasMountButton: true' "$DOC"
grep -Fq 'panelHasMountOutput: true' "$DOC"
grep -Fq 'doesNotReturnQuestionText: true' "$DOC"
grep -Fq 'doesNotReturnAnswerText: true' "$DOC"
grep -Fq 'noBackendAllowed: true' "$DOC"
grep -Fq 'noModelAllowed: true' "$DOC"
grep -Fq 'noAnkiWriteAllowed: true' "$DOC"
grep -Fq 'adapter present: yes' "$DOC"
grep -Fq 'adapter rendered: yes' "$DOC"
grep -Fq 'deck: Anki Deck2' "$DOC"
grep -Fq 'mounted: true` closes the Stage 17K-S adapter mount repair' "$DOC"
grep -Fq 'No Anki question text or answer text was saved to repo docs' "$DOC"
echo "PASS: Stage 17K-S-R3 live proof smoke passed"
