#!/usr/bin/env bash
set -euo pipefail

DOC="docs/phase-14j-fl-website-edge-cloudflared-install-only.md"

echo "=== Phase 14J-FL smoke: website-edge cloudflared install-only record ==="

test -f "$DOC"

require_marker() {
  local marker="$1"
  if grep -Fq -- "$marker" "$DOC"; then
    echo "PASS: marker present: $marker"
  else
    echo "FAIL: marker missing: $marker" >&2
    exit 1
  fi
}

require_marker "PHASE_14J_FL_WEBSITE_EDGE_CLOUDFLARED_INSTALL_ONLY"
require_marker "Previous commit: 4c962c4"
require_marker "MUTATION_SCOPE=website_edge_vm_200_cloudflared_install_only"
require_marker "hostname=website-edge"
require_marker "os_version=26.04"
require_marker "PASS: nginx service active before FL"
require_marker "PASS: nginx config test passed before FL"
require_marker "PASS: command absent before fl: docker"
require_marker "PASS: command absent before fl: node"
require_marker "PASS: command absent before fl: npm"
require_marker "PASS: cloudflared absent before FL"
require_marker "pre_fl_root_index_html_status=200"
require_marker "pre_fl_app_js_status=200"
require_marker "pre_fl_styles_css_status=200"
require_marker "pre_fl_queued_chat_config_js_status=200"
require_marker "download_source=official_cloudflare_github_latest_release"
require_marker "download_kind=linux-amd64-binary"
require_marker "download_url_printed=no"
require_marker "download_size_bytes=39244160"
require_marker "download_sha256=08d27c4c5d3ed73ee3e98ef2ddceb4ad09fd4cfc28e243565a189538e8ccd706"
require_marker "downloaded_cloudflared_version=cloudflared version 2026.6.0"
require_marker "PASS: downloaded cloudflared binary version check passed"
require_marker "PASS: cloudflared binary installed to expected path"
require_marker "installed_cloudflared_path=/usr/local/bin/cloudflared"
require_marker "PASS: cloudflared resolves to expected install path"
require_marker "installed_cloudflared_sha256=08d27c4c5d3ed73ee3e98ef2ddceb4ad09fd4cfc28e243565a189538e8ccd706"
require_marker "PASS: installed cloudflared hash matches downloaded binary"
require_marker "installed_cloudflared_version=cloudflared version 2026.6.0"
require_marker "PASS: installed cloudflared version check passed"
require_marker "PASS: no cloudflared systemd unit exists after install-only phase"
require_marker "PASS: no cloudflared process running after install-only phase"
require_marker "home_cloudflared_file_count=0"
require_marker "cloudflare_token_used=no"
require_marker "cloudflare_tunnel_authenticated=no"
require_marker "cloudflare_route_mutation_performed=no"
require_marker "cloudflare_test_hostname_created=no"
require_marker "cloudflare_production_cutover_performed=no"
require_marker "PASS: nginx service active after FL"
require_marker "PASS: nginx config test passed after FL"
require_marker "post_fl_root_index_html_status=200"
require_marker "post_fl_app_js_status=200"
require_marker "post_fl_styles_css_status=200"
require_marker "post_fl_queued_chat_config_js_status=200"
require_marker "PASS: command absent after fl: docker"
require_marker "PASS: command absent after fl: node"
require_marker "PASS: command absent after fl: npm"
require_marker "website_edge_source_git_status_after=<clean>"
require_marker "PASS: website-edge source checkout remains clean after FL"
require_marker "cloudflared_systemd_unit_created_or_enabled=no"
require_marker "cloudflared_process_running_after_install=no"
require_marker "nginx_config_mutation_performed=no"
require_marker "app_systemd_runtime_creation_performed=no"
require_marker "docker_install_performed=no"
require_marker "node_npm_install_performed=no"
require_marker "tailscale_acl_grants_tag_mutation_performed=no"
require_marker "tailscale_ssh_mode_enablement_performed=no"
require_marker "subnet_routes_created=no"
require_marker "exit_node_enabled=no"
require_marker "proxmox_mutation_performed=no"
require_marker "controller_queue_migration_performed=no"
require_marker "worker_start_performed=no"
require_marker "production_db_job_mutation_performed=no"
require_marker "ct101_call_performed=no"
require_marker "model_ollama_endpoint_call_performed=no"
require_marker "phase_14j_ag_apply_wrapper_rerun_performed=no"
require_marker "PHASE_14J_FL_RESULT=passed"
require_marker "cloudflared_install_only=passed"
require_marker "rollback_performed=no"
require_marker "phase_exit_code=0"
require_marker "PHASE_14J_FL_RESULT=website_edge_cloudflared_install_only_recorded"
require_marker "NEXT_SAFE_PHASE=plan_website_edge_cloudflared_tunnel_token_setup_for_temporary_test_hostname_without_production_cutover"

echo "PASS: Phase 14J-FL website-edge cloudflared install-only record is complete"
