#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-fc-o45-e-bc-deploy-companion-clean-chat-workspace-over-tailscale-restricted-path.md"
APP_JS="frontend/wrapper-ui/app.js"
STYLE_CSS="frontend/wrapper-ui/styles.css"

test -f "$DOC"
test -f "$APP_JS"
test -f "$STYLE_CSS"

grep -Fq "Stage 16 FC-O45-E-BC" "$DOC"
grep -Fq "APPROVE_FC_O45_E_BC_DEPLOY_COMPANION_CLEAN_CHAT_WORKSPACE_OVER_TAILSCALE_RESTRICTED_PATH" "$DOC"
grep -Fq "apcdeploy@website-edge" "$DOC"
grep -Fq "No QGA package transfer was used" "$DOC"
grep -Fq "/app.js?v=20260624fc045ebc" "$DOC"
grep -Fq "restricted_tailscale_deploy=PASS" "$DOC"
grep -Fq "post_public_verification=PASS" "$DOC"
grep -Fq "FC_O45_E_BC_DEPLOY_RECORDED" "$DOC"
grep -Fq "Chat with your Companion" "$DOC"
grep -Fq "Enter sends the message" "$DOC"
grep -Fq "Shift+Enter inserts a newline" "$DOC"
grep -Fq "fallback: qwen2.5:0.5b" "$DOC"
grep -Fq "NO DB write" "$DOC"
grep -Fq "NO backend API deploy" "$DOC"
grep -Fq "NO service restart" "$DOC"

grep -Fq "Companion result reader" "$APP_JS"
grep -Fq "Stage 16 FC-O45-E-AS Companion Immersion Mode scaffold" "$APP_JS"
grep -Fq "Stage 16 FC-O45-E-AT Companion Immersion visible panel source wiring" "$APP_JS"
grep -Fq "Stage 16 FC-O45-E-AZ Companion Immersion primary workspace placement" "$APP_JS"
grep -Fq "Stage 16 FC-O45-E-BB Companion clean chat workspace" "$APP_JS"
grep -Fq "window.apcCompanionImmersionRuntime" "$APP_JS"
grep -Fq "window.apcCompanionImmersionPrimaryWorkspace" "$APP_JS"
grep -Fq "window.apcCompanionCleanChatWorkspace" "$APP_JS"
grep -Fq "apcCompanionImmersionObservedFetch" "$APP_JS"
grep -Fq "installEnterToSend" "$APP_JS"
grep -Fq "Chat with your Companion" "$APP_JS"
grep -Fq "Type a message and press Enter to send." "$APP_JS"
grep -Fq "companion-clean-hidden" "$APP_JS"
grep -Fq "fallback: qwen2.5:0.5b" "$APP_JS"

grep -Fq "Stage 16 FC-O45-E-AT Companion Immersion visible panel CSS wiring" "$STYLE_CSS"
grep -Fq "Stage 16 FC-O45-E-AZ Companion Immersion primary workspace CSS" "$STYLE_CSS"
grep -Fq "Stage 16 FC-O45-E-BB Companion clean chat workspace CSS" "$STYLE_CSS"
grep -Fq "#companionImmersionPrimaryWorkspace" "$STYLE_CSS"
grep -Fq ".companion-clean-hidden" "$STYLE_CSS"

echo "PASS: Stage 16 FC-O45-E-BC deploy Companion clean chat workspace over Tailscale restricted path smoke"
