#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3y-g-final-one-shot-scheduler-runtime-closure-read-only.md"

echo "=== Stage 16 E3Y-G smoke: final one-shot scheduler runtime closure read-only ==="

test -s "$DOC"

grep -F "Final One-Shot Scheduler Runtime Closure, Read-Only" "$DOC"
grep -F "E3Y_G_FINAL_ONE_SHOT_SCHEDULER_RUNTIME_CLOSURE_READ_ONLY_OK" "$DOC"
grep -F "HEAD/origin/main/remote: f54776e" "$DOC"
grep -F "job_id=32" "$DOC"
grep -F "status=completed" "$DOC"
grep -F "attempts=1" "$DOC"
grep -F "requested_model=qwen2.5:0.5b" "$DOC"
grep -F "job_type=stage16_e3y_scheduler_one_shot_small_model_completion_smoke" "$DOC"
grep -F "result_rows=1" "$DOC"
grep -F "classification=completed_with_one_result" "$DOC"
grep -F "queued job -> one-shot scheduler approval -> scheduler wrapper -> timeout-safe wrapper delegation -> atomic claim -> bounded PVESO Ollama call -> completion transaction -> one job_results row" "$DOC"
grep -F "job 29: failed, attempts=1, result_rows=0" "$DOC"
grep -F "job 30: failed, attempts=1, result_rows=0" "$DOC"
grep -F "job 31: completed, attempts=1, result_rows=1" "$DOC"
grep -F "job 32: completed, attempts=1, result_rows=1" "$DOC"
grep -F "DB_INTEGRITY=ok" "$DOC"
grep -F "JOBS_TOTAL=31" "$DOC"
grep -F "JOB_RESULTS_TOTAL=12" "$DOC"
grep -F "DUPLICATE_JOB_RESULTS none" "$DOC"
grep -F "E3Y_G_RUNNING_STAGE16_PROOF_JOB_COUNT=0" "$DOC"
grep -F "E3Y_G_QUEUED_STAGE16_PROOF_JOB_COUNT=0" "$DOC"
grep -F "E3Y_G_ONE_SHOT_SCHEDULER_RUNTIME_CLASSIFICATION=completed_with_one_result" "$DOC"
grep -F "E3Y_G_DB_CLOSURE_OK" "$DOC"
grep -F "E3Y_G_ONE_SHOT_SCHEDULER_WRAPPER_PRESENT=true" "$DOC"
grep -F "E3Y_G_ONE_SHOT_SCHEDULER_HAS_DRY_RUN_PATH=true" "$DOC"
grep -F "E3Y_G_ONE_SHOT_SCHEDULER_HAS_RUN_DELEGATION_PATH=true" "$DOC"
grep -F "E3Y_G_REPO_CLOSURE_OK" "$DOC"
grep -F "OLLAMA_SERVICE_STATE=active" "$DOC"
grep -F "OLLAMA_NONLOCALHOST_11434_LISTENER_COUNT=0" "$DOC"
grep -F "PVESO_ACTIVE_MODEL_CLIENT_COUNT=0" "$DOC"
grep -F "CT101_STATUS=stopped" "$DOC"
grep -F "CT101_ONBOOT=0" "$DOC"
grep -F "E3Y_G_SMALL_MODEL_VISIBLE_TO_HOST_OLLAMA=true" "$DOC"
grep -F "E3Y_G_PVESO_CLOSURE_OK" "$DOC"
grep -F "Persistent scheduler activation remains blocked" "$DOC"
grep -F "Persistent workers remain disabled" "$DOC"
grep -F "E3Z-A — persistent scheduler activation readiness plan, no activation" "$DOC"
grep -F "Do not rerun E3V-Q" "$DOC"
grep -F "Do not retry job 29" "$DOC"
grep -F "Do not rerun job 30" "$DOC"
grep -F "Do not rerun job 31" "$DOC"
grep -F "Do not rerun job 32 without a new explicit plan and approval" "$DOC"

echo "E3Y_G_FINAL_ONE_SHOT_SCHEDULER_RUNTIME_CLOSURE_READ_ONLY_SMOKE_OK"
