#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3z-a-persistent-scheduler-activation-readiness-plan-no-activation.md"

echo "=== Stage 16 E3Z-A smoke: persistent scheduler activation readiness no activation ==="

test -s "$DOC"

grep -F "Persistent Scheduler Activation Readiness Plan, No Activation" "$DOC"
grep -F "E3Z_A_PERSISTENT_SCHEDULER_ACTIVATION_READINESS_PLAN_NO_ACTIVATION_OK" "$DOC"
grep -F "HEAD/origin/main/remote: 332d1c6" "$DOC"
grep -F "queued job -> one-shot scheduler approval -> scheduler wrapper -> timeout-safe wrapper delegation -> atomic claim -> bounded PVESO Ollama call -> completion transaction -> one job_results row" "$DOC"
grep -F "job_id=32" "$DOC"
grep -F "status=completed" "$DOC"
grep -F "attempts=1" "$DOC"
grep -F "requested_model=qwen2.5:0.5b" "$DOC"
grep -F "result_rows=1" "$DOC"
grep -F "DB_INTEGRITY=ok" "$DOC"
grep -F "JOBS_TOTAL=31" "$DOC"
grep -F "JOB_RESULTS_TOTAL=12" "$DOC"
grep -F "DUPLICATE_JOB_RESULTS none" "$DOC"
grep -F "E3Z_A_RUNNING_STAGE16_PROOF_JOB_COUNT=0" "$DOC"
grep -F "E3Z_A_QUEUED_STAGE16_PROOF_JOB_COUNT=0" "$DOC"
grep -F "E3Z_A_DB_CLOSURE_OK" "$DOC"
grep -F "E3Z_A_CT203_ACTIVATION_SURFACE_OK" "$DOC"
grep -F "E3Z_A_ONE_SHOT_SCHEDULER_PROOF_PRESENT=true" "$DOC"
grep -F "E3Z_A_TIMEOUT_SAFE_WRAPPER_PROOF_PRESENT=true" "$DOC"
grep -F "E3Z_A_PERSISTENT_ACTIVATION_NOT_REQUESTED=true" "$DOC"
grep -F "E3Z_A_REPO_ACTIVATION_SURFACE_OK" "$DOC"
grep -F "The platform is ready to design persistent scheduler activation, but not ready to activate it in this phase." "$DOC"
grep -F "Persistent scheduler activation remains blocked" "$DOC"
grep -F "Persistent workers remain disabled" "$DOC"
grep -F "E3Z-B — persistent scheduler service/timer design, no activation" "$DOC"
grep -F "E3Z-E — optionally source refresh and new-chat handoff" "$DOC"
grep -F "A fresh proof job only, not jobs 29, 30, 31, or 32" "$DOC"
grep -F "E3Z-A did not:" "$DOC"
grep -F "activate scheduler" "$DOC"
grep -F "activate persistent workers" "$DOC"
grep -F "enable, start, restart, or reload services or timers" "$DOC"
grep -F "Do not rerun E3V-Q" "$DOC"
grep -F "Do not retry job 29" "$DOC"
grep -F "Do not rerun job 30" "$DOC"
grep -F "Do not rerun job 31" "$DOC"
grep -F "Do not rerun job 32 without a new explicit plan and approval" "$DOC"

echo "E3Z_A_PERSISTENT_SCHEDULER_ACTIVATION_READINESS_PLAN_NO_ACTIVATION_SMOKE_OK"
