#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3y-a-scheduler-integration-readiness-plan-no-activation.md"

echo "=== Stage 16 E3Y-A smoke: scheduler integration readiness plan no activation ==="

test -s "$DOC"

grep -F "Scheduler Integration Readiness Plan, No Activation" "$DOC"
grep -F "E3Y_A_SCHEDULER_INTEGRATION_READINESS_PLAN_NO_ACTIVATION_OK" "$DOC"
grep -F "HEAD/origin/main/remote: 9c1c509" "$DOC"
grep -F "queued job -> atomic claim -> bounded PVESO Ollama call -> completion transaction -> one job_results row" "$DOC"
grep -F "job_id=31" "$DOC"
grep -F "requested_model=qwen2.5:0.5b" "$DOC"
grep -F "status=completed" "$DOC"
grep -F "attempts=1" "$DOC"
grep -F "result_rows=1" "$DOC"
grep -F "DB_INTEGRITY=ok" "$DOC"
grep -F "JOBS_TOTAL=30" "$DOC"
grep -F "JOB_RESULTS_TOTAL=11" "$DOC"
grep -F "DUPLICATE_JOB_RESULTS none" "$DOC"
grep -F "E3Y_A_RUNNING_E3V_E3W_E3X_E3Y_JOB_COUNT=0" "$DOC"
grep -F "E3Y_A_QUEUED_E3V_E3W_E3X_E3Y_JOB_COUNT=0" "$DOC"
grep -F "E3Y_A_COMPLETED_SMALL_MODEL_PROOF_CONFIRMED=true" "$DOC"
grep -F "E3Y_A_DB_READINESS_OK" "$DOC"
grep -F "E3Y_A_WRAPPER_HAS_APPROVAL_COMPAT_SHIM=true" "$DOC"
grep -F "E3Y_A_WRAPPER_HAS_ATOMIC_CLAIM_PATH=true" "$DOC"
grep -F "E3Y_A_WRAPPER_HAS_COMPLETION_PATH=true" "$DOC"
grep -F "E3Y_A_WRAPPER_HAS_INTERNAL_FAILURE_PATH=true" "$DOC"
grep -F "E3Y_A_REPO_SCHEDULER_READINESS_OK" "$DOC"
grep -F "OLLAMA_SERVICE_STATE=active" "$DOC"
grep -F "OLLAMA_NONLOCALHOST_11434_LISTENER_COUNT=0" "$DOC"
grep -F "PVESO_ACTIVE_MODEL_CLIENT_COUNT=0" "$DOC"
grep -F "CT101_STATUS=stopped" "$DOC"
grep -F "CT101_ONBOOT=0" "$DOC"
grep -F "E3Y_A_SMALL_MODEL_VISIBLE_TO_HOST_OLLAMA=true" "$DOC"
grep -F "E3Y_A_PVESO_READINESS_OK" "$DOC"
grep -F "No job may remain running after wrapper exit" "$DOC"
grep -F "Persistent workers remain disabled" "$DOC"
grep -F "E3Y-B — scheduler one-shot design, no activation" "$DOC"
grep -F "E3Y-E — approved one-shot scheduler runtime proof" "$DOC"
grep -F "E3Y-A did not:" "$DOC"
grep -F "activate scheduler" "$DOC"
grep -F "activate persistent workers" "$DOC"
grep -F "call a model" "$DOC"
grep -F "Do not rerun E3V-Q" "$DOC"
grep -F "Do not retry job 29" "$DOC"
grep -F "Do not rerun job 30" "$DOC"
grep -F "Do not rerun job 31 without a new explicit plan and approval" "$DOC"

echo "E3Y_A_SCHEDULER_INTEGRATION_READINESS_PLAN_NO_ACTIVATION_SMOKE_OK"
