#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-17k-r14f-record-save-action-controller-asset-not-loaded-proof.md"
OUT_DIR="docs/smoke/generated/stage-17k-r14f-record-save-action-controller-asset-not-loaded-proof"

test -f "$DOC"
test -d "$OUT_DIR"

grep -Fq "Record Save Action Controller Asset-Not-Loaded Proof" "$DOC"
grep -Fq "Browser proof passed" "$DOC"
grep -Fq "PASS_R14E_SAVE_ACTION_CONTROLLER_ASSET_NOT_LOADED" "$DOC"
grep -Fq "controllerAssetStatus 200" "$DOC"
grep -Fq "controllerHasMarker true" "$DOC"
grep -Fq "controllerHasStateFunction true" "$DOC"
grep -Fq "controllerHasViewModelFunction true" "$DOC"
grep -Fq "controllerHasNoWriteFlags true" "$DOC"
grep -Fq "APC_LOCAL_BACKUP_CURRENT_FILE_SAVE_ACTION_CONTROLLER_R14D_SOURCE_ONLY" "$DOC"
grep -Fq "createSaveCurrentBackupActionState" "$DOC"
grep -Fq "createDisabledActionViewModel" "$DOC"
grep -Fq "executorCallAllowedNow: false" "$DOC"
grep -Fq "writesEnabledNow: false" "$DOC"
grep -Fq "canWriteNow: false" "$DOC"
grep -Fq "controllerLoadedByScript false" "$DOC"
grep -Fq "controllerWindowPresent false" "$DOC"
grep -Fq "executorWindowPresent true" "$DOC"
grep -Fq "savePlanPreviewStillVisible true" "$DOC"
grep -Fq "hasUnsafeButton false" "$DOC"
grep -Fq "mountStatus 200" "$DOC"
grep -Fq "panelStatus 200" "$DOC"
grep -Fq "mountReferencesController false" "$DOC"
grep -Fq "panelReferencesController false" "$DOC"
grep -Fq "Choose local backup folder" "$DOC"
grep -Fq "Download snapshot" "$DOC"
grep -Fq "Preview backup file" "$DOC"
grep -Fq "Open current backup file" "$DOC"
grep -Fq "No source mutation" "$DOC"
grep -Fq "No current-file save in live UI" "$DOC"
grep -Fq "No same-file write path in live UI" "$DOC"

echo "PASS stage-17k-r14f record save action controller asset-not-loaded proof smoke"
