#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3v-n-runtime-atomic-claim-dispatch-plan-no-apply.md"

echo "=== Stage 16 E3V-N smoke: runtime atomic-claim dispatch plan, no apply ==="

test -s "$DOC"

grep -F "No Apply" "$DOC" || grep -F "no-apply" "$DOC"
grep -F "does not run the dispatch" "$DOC"
grep -F "does not execute the wrapper" "$DOC"
grep -F "does not write the DB" "$DOC"
grep -F "does not claim job 29" "$DOC"
grep -F "does not call a model" "$DOC"
grep -F "HEAD/origin/main: 7843a44" "$DOC"
grep -F "E3V_DRY_RUN_ELIGIBLE_JOB_COUNT=1" "$DOC"
grep -F "E3V_DRY_RUN_RESULT=WOULD_CLAIM_ONE_JOB_NO_RUNTIME" "$DOC"
grep -F "WOULD_ATOMIC_CLAIM job_id=29" "$DOC"
grep -F "REFUSE_E3V_EXECUTE_NOT_ENABLED" "$DOC"
grep -F "APPROVE_STAGE_16_E3V_Q_RUN_JOB_29_OPTION_B_ATOMIC_CLAIM_DISPATCH_ONLY" "$DOC"
grep -F "job_id=29 only" "$DOC"
grep -F "selected job id is exactly 29" "$DOC"
grep -F "job 29 status=queued" "$DOC"
grep -F "job 29 attempts=0" "$DOC"
grep -F "job 29 result_rows=0" "$DOC"
grep -F "qwen2.5:32b-instruct-q4_K_M" "$DOC"
grep -F "OLLAMA_NONLOCALHOST_11434_LISTENER_COUNT=0" "$DOC"
grep -F "PVESO_RUNNER_OR_ADAPTER_PROCESS_COUNT=0" "$DOC"
grep -F "BEGIN IMMEDIATE" "$DOC"
grep -F "UPDATE jobs" "$DOC"
grep -F "SET status='running'" "$DOC"
grep -F "attempts=attempts+1" "$DOC"
grep -F "SELECT changes()" "$DOC"
grep -F "E3V_Q_ATOMIC_CLAIM_CHANGES=1" "$DOC"
grep -F "REFUSE_ATOMIC_CLAIM_NOT_ONE" "$DOC"
grep -F "ONE_SHOT_MODEL_ADAPTER_RESULT=ok" "$DOC"
grep -F "SET status='completed'" "$DOC"
grep -F "INSERT INTO job_results" "$DOC"
grep -F "E3V_Q_COMPLETION_CHANGES=1" "$DOC"
grep -F "E3V_Q_JOB_STATUS_AFTER_COMPLETION=completed" "$DOC"
grep -F "E3V_Q_JOB_RESULT_ROWS_AFTER_COMPLETION=1" "$DOC"
grep -F "E3V_Q_OPTION_B_ATOMIC_CLAIM_DISPATCH_JOB_29_OK" "$DOC"
grep -F "DO_NOT_RERUN" "$DOC"
grep -F "RUN_READ_ONLY_RECOVERY_FIRST" "$DOC"
grep -F "completed_with_one_result_do_not_rerun" "$DOC"
grep -F "REFUSE_SELECTED_JOB_ID_NOT_29" "$DOC"
grep -F "REFUSE_COMPLETION_NOT_ONE" "$DOC"
grep -F "Runtime remains blocked by E3V-N" "$DOC"
grep -F "No atomic claim dispatch is approved" "$DOC"

echo "E3V_N_RUNTIME_ATOMIC_CLAIM_DISPATCH_PLAN_NO_APPLY_SMOKE_OK"
