#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3y-d-implement-one-shot-scheduler-wrapper-no-run.md"
SCHED="ops/scheduler/stage-16-e3y-one-shot-scheduler-dispatch.sh"

echo "=== Stage 16 E3Y-D smoke: implement one-shot scheduler wrapper no run ==="

test -s "$DOC"
test -x "$SCHED"
bash -n "$SCHED"

grep -F "Implement One-Shot Scheduler Wrapper, No Run" "$DOC"
grep -F "E3Y_D_IMPLEMENT_ONE_SHOT_SCHEDULER_WRAPPER_NO_RUN_OK" "$DOC"
grep -F "HEAD/origin/main/remote: 3e7acf3" "$DOC"
grep -F "job_id=32" "$DOC"
grep -F "requested_model=qwen2.5:0.5b" "$DOC"
grep -F "job_type=stage16_e3y_scheduler_one_shot_small_model_completion_smoke" "$DOC"
grep -F "status=queued" "$DOC"
grep -F "attempts=0" "$DOC"
grep -F "result_rows=0" "$DOC"
grep -F "E3Y_D_DB_READINESS_OK" "$DOC"
grep -F "E3Y_D_STATIC_VALIDATION_OK" "$DOC"
grep -F "ops/scheduler/stage-16-e3y-one-shot-scheduler-dispatch.sh" "$DOC"
grep -F "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_WOULD_SELECT_JOB" "$DOC"
grep -F "APPROVE_STAGE_16_E3Y_F_RUN_ONE_SHOT_SCHEDULER_SMALL_MODEL_JOB_ONLY" "$DOC"
grep -F "APPROVE_STAGE_16_E3X_E_RUN_ONE_SMALL_MODEL_TIMEOUT_SAFE_JOB_ONLY" "$DOC"
grep -F "It does not install, enable, start, or restart any scheduler service" "$DOC"
grep -F "It does not activate persistent workers" "$DOC"
grep -F "E3Y-D did not:" "$DOC"
grep -F "claim job 32" "$DOC"
grep -F "execute the scheduler wrapper" "$DOC"
grep -F "call a model" "$DOC"
grep -F "activate scheduler" "$DOC"
grep -F "activate persistent workers" "$DOC"
grep -F "E3Y-E — dry-run one-shot scheduler would select job 32" "$DOC"
grep -F "E3Y-E must not claim job 32, call a model, or write the DB" "$DOC"
grep -F "Do not rerun E3V-Q" "$DOC"
grep -F "Do not retry job 29" "$DOC"
grep -F "Do not rerun job 30" "$DOC"
grep -F "Do not rerun job 31" "$DOC"
grep -F "Use job 32 only for the E3Y scheduler one-shot proof path" "$DOC"

grep -F "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_ONLY" "$SCHED"
grep -F "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_WOULD_SELECT_JOB" "$SCHED"
grep -F "E3Y_ONE_SHOT_SCHEDULER_RUN_MODE_APPROVAL_REQUIRED" "$SCHED"
grep -F "E3Y_ONE_SHOT_SCHEDULER_DELEGATING_TO_TIMEOUT_SAFE_WRAPPER=true" "$SCHED"
grep -F '"$WRAPPER" --dry-run' "$SCHED"
grep -F '"$WRAPPER" --run' "$SCHED"

echo "E3Y_D_IMPLEMENT_ONE_SHOT_SCHEDULER_WRAPPER_NO_RUN_SMOKE_OK"
