#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-17k-r14a-record-manual-executor-fake-handle-proof.md"
OUT_DIR="docs/smoke/generated/stage-17k-r14a-record-manual-executor-fake-handle-proof"

test -f "$DOC"
test -d "$OUT_DIR"

grep -Fq "Record Manual Executor Fake-Handle Proof" "$DOC"
grep -Fq "Browser console proof passed" "$DOC"
grep -Fq "PASS_R14A_MANUAL_EXECUTOR_FAKE_HANDLE_PROOF" "$DOC"
grep -Fq "beforeLoaded false" "$DOC"
grep -Fq "hasExecutorAfterManualLoad true" "$DOC"
grep -Fq "APC_LOCAL_BACKUP_CURRENT_FILE_WRITE_EXECUTOR_R13X_SOURCE_ONLY" "$DOC"
grep -Fq "hasWriter true" "$DOC"
grep -Fq "planSelectedFileAllowed true" "$DOC"
grep -Fq "planWriterPlanReady true" "$DOC"
grep -Fq "planRemovedFieldCount 4" "$DOC"
grep -Fq "planAfterLegacyFieldPaths []" "$DOC"
grep -Fq "refusedExecuted false" "$DOC"
grep -Fq "refusedRefused true" "$DOC"
grep -Fq "enableWrite is not true" "$DOC"
grep -Fq "enableToken does not match" "$DOC"
grep -Fq "confirmSelectedFileName does not match buddies-who-study-current.json" "$DOC"
grep -Fq "executedExecuted true" "$DOC"
grep -Fq "executedWrotePrevious true" "$DOC"
grep -Fq "executedWroteCurrent true" "$DOC"
grep -Fq "executedReadbackVerified true" "$DOC"
grep -Fq "executedReadbackLegacyFieldPaths []" "$DOC"
grep -Fq "previousFakeText OLD_CURRENT_BACKUP_TEXT" "$DOC"
grep -Fq "currentHasSanitizedPrivacy true" "$DOC"
grep -Fq "currentHasLegacyBackendProgress false" "$DOC"
grep -Fq "fake in-memory file handles only" "$DOC"
grep -Fq "No source mutation" "$DOC"
grep -Fq "No current-file save in live UI" "$DOC"
grep -Fq "No same-file write path in live UI" "$DOC"

echo "PASS stage-17k-r14a record manual executor fake-handle proof smoke"
