#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

DOC="docs/stage-16-fc-o45-e-cl-c-r2-companion-route-backlog-pinpoint.md"

test -f "$DOC"

check() {
  local needle="$1"
  grep -Fq "$needle" "$DOC"
}

check "Companion Route and Backlog Pinpoint"
check "41db87e"
check "1eb84e48c6835741abc31fbd68acb759a690af3d026a96d6d284540cde0072a2"
check "16d5e145ee3fc917ff8474f82dac4c91ce4d6397c4cea54c0f1b4f3bc560af6f"
check "edge-queue-scheduler-one-shot.timer active=inactive enabled=disabled"
check "edge-queue-scheduler-one-shot.service active=inactive enabled=static"
check "edge-deterministic-companion-worker-once@999999.service active=inactive enabled=static"
check "/api/companion/chat"
check "/public/companion/chat"
check "/api/companion/jobs/{job_id}/result"
check "/api/companion/study/action"
check "/public/companion/study/action"
check "/api/companion/context"
check "/public/companion/context"
check "/api/companion/voice/status"
check "/api/companion/voice/action"
check "companion_execution"
check "deterministic_exact_answer_short_circuit"
check "backend-deterministic/no-model"
check "JSONDecodeError: Expecting value"
check "CL_C_R2_CLEANUP_TOOL_OK=True"
check "CL_C_R2_CLEANUP_TOOL_MODE=read_only"
check "CL_C_R2_CLEANUP_TOOL_CANDIDATE_COUNT=0"
check "CL_C_R2_CLEANUP_TOOL_ID_SHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
check "CL_C_R2_CLEANUP_TOOL_MUTATED=False"
check "CL_C_R2_DB_INTEGRITY=ok"
check "CL_C_R2_JOBS_TOTAL=576"
check "CL_C_R2_RESULTS_TOTAL=83"
check "CL_C_R2_QUEUED_COMPANION=0"
check "CL_C_R2_CLEANUP_ROWS=440"
check "CL_C_R2_QUEUED_ANY=25"
check "CL_C_R2_RUNNING_ANY=10"
check "CL_C_R2_CK_Y_JOB id=581 status=completed attempts=1 requested_model=qwen2.5:0.5b result_rows=1 result_model=backend-deterministic/no-model response_text=FC-O45-E-CK-Y-POST-CLEANUP-SELECTOR-OK"
check "job_type=ollama_chat status=queued count=1"
check "job_type=stage16_e3z_limited_persistent_worker_repeat_proof status=queued count=6"
check "job_type=stage16_e3z_limited_persistent_worker_repeat_proof status=running count=3"
check "job_type=stage16_fc_companion_chat_semantic_probe status=running count=2"
check "GET /api/system/status => HTTP 200"
check "GET /api/companion/voice/status => HTTP 200"
check "GET /api/companion/context => HTTP 401 Missing bearer token"
check "POST /api/companion/chat => HTTP 401 Missing bearer token"
check "POST /api/companion/study/action => HTTP 401 Missing bearer token"
check "GET /api/companion/jobs/581/result => HTTP 401 Missing bearer token"
check "queued_companion=0"
check "cleanup_tool_candidate_count=0"
check "queued_any=25"
check "running_any=10"
check "authenticated Companion/Study last-message MVP patch"

echo "PASS stage-16-fc-o45-e-cl-d companion route/backlog pinpoint record smoke"
