#!/usr/bin/env bash
set -euo pipefail

WRAPPER="ops/scheduler/stage-16-e3v-run-one-existing-status-atomic-claim-dispatch.sh"

echo "=== Stage 16 E3V-F smoke: static Option B wrapper artifact, no runtime ==="

test -s "$WRAPPER"
test -x "$WRAPPER"

grep -F "STATIC_ARTIFACT_STATUS=created_not_runtime_enabled" "$WRAPPER"
grep -F "DEFAULT_REFUSAL=true" "$WRAPPER"
grep -F "REFUSE_MODE_REQUIRED" "$WRAPPER"
grep -F "REFUSE_UNKNOWN_MODE" "$WRAPPER"
grep -F "REFUSE_E3V_RUNTIME_NOT_IMPLEMENTED_IN_STATIC_ARTIFACT" "$WRAPPER"
grep -F "NO_DB_WRITE" "$WRAPPER"
grep -F "NO_SCHEMA_MIGRATION" "$WRAPPER"
grep -F "NO_DB_CLAIM" "$WRAPPER"
grep -F "NO_HELPER_CALL" "$WRAPPER"
grep -F "NO_ADAPTER_CALL" "$WRAPPER"
grep -F "NO_MODEL_CALL" "$WRAPPER"
grep -F "SCHEDULER_ACTIVATION=not_performed" "$WRAPPER"
grep -F "PERSISTENT_WORKER_ACTIVATION=not_performed" "$WRAPPER"
grep -F -- "--dry-run" "$WRAPPER"
grep -F -- "--execute-approved" "$WRAPPER"
grep -F "APPROVE_STAGE_16_E3V_RUN_ONE_EXISTING_STATUS_ATOMIC_CLAIM_DISPATCH_ONLY" "$WRAPPER"
grep -F "E3V_OPTION_B_ATOMIC_CLAIM_ONE_SHOT_DISPATCH_OK" "$WRAPPER"
grep -F "REFUSE_APPROVAL_MISSING" "$WRAPPER"
grep -F "REFUSE_REPO_CHECKPOINT_MISMATCH" "$WRAPPER"
grep -F "REFUSE_REPO_DIRTY" "$WRAPPER"
grep -F "REFUSE_SCHEDULER_ACTIVE" "$WRAPPER"
grep -F "REFUSE_PERSISTENT_WORKERS_ACTIVE" "$WRAPPER"
grep -F "REFUSE_CT101_NOT_STOPPED" "$WRAPPER"
grep -F "REFUSE_PVESO_UNAVAILABLE" "$WRAPPER"
grep -F "REFUSE_OLLAMA_NOT_LOCALHOST_ONLY" "$WRAPPER"
grep -F "REFUSE_MODEL_MISSING" "$WRAPPER"
grep -F "REFUSE_NO_ELIGIBLE_JOB" "$WRAPPER"
grep -F "REFUSE_MULTIPLE_ELIGIBLE_JOBS" "$WRAPPER"
grep -F "REFUSE_FORBIDDEN_JOB_ID" "$WRAPPER"
grep -F "REFUSE_SELECTED_JOB_NOT_QUEUED" "$WRAPPER"
grep -F "REFUSE_SELECTED_JOB_HAS_RESULT" "$WRAPPER"
grep -F "REFUSE_ATOMIC_CLAIM_NOT_ONE" "$WRAPPER"
grep -F "REFUSE_COMPLETION_NOT_ONE" "$WRAPPER"
grep -F "23" "$WRAPPER"
grep -F "24" "$WRAPPER"
grep -F "27" "$WRAPPER"
grep -F "28" "$WRAPPER"
grep -F "qwen2.5:32b-instruct-q4_K_M" "$WRAPPER"
grep -F "BEGIN IMMEDIATE" "$WRAPPER"
grep -F "UPDATE jobs" "$WRAPPER"
grep -F "SET status='running'" "$WRAPPER"
grep -F "attempts=attempts+1" "$WRAPPER"
grep -F "SELECT changes()" "$WRAPPER"
grep -F "changes() == 1" "$WRAPPER"
grep -F "status=running" "$WRAPPER"
grep -F "SET status='completed'" "$WRAPPER"
grep -F "INSERT INTO job_results" "$WRAPPER"
grep -F "job_results_for_job_after=1" "$WRAPPER"
grep -F "pveso_runner_count_after=0" "$WRAPPER"
grep -F "ct101_status_after=stopped" "$WRAPPER"
grep -F "ct101_onboot_after=0" "$WRAPPER"
grep -F "derive PVESO from Tailscale status, not hardcoded pveso DNS" "$WRAPPER"
grep -F "OLLAMA_LOCALHOST_11434_LISTENER_COUNT=1" "$WRAPPER"
grep -F "OLLAMA_NONLOCALHOST_11434_LISTENER_COUNT=0" "$WRAPPER"
grep -F "CT101_STATUS=stopped" "$WRAPPER"
grep -F "CT101_ONBOOT=0" "$WRAPPER"
grep -F "DO_NOT_RERUN" "$WRAPPER"
grep -F "RUN_READ_ONLY_RECOVERY_FIRST" "$WRAPPER"
grep -F "completed_with_one_result_do_not_rerun" "$WRAPPER"
grep -F "running_zero_results_runner_active_do_not_rerun" "$WRAPPER"
grep -F "duplicate_result_failure_do_not_rerun" "$WRAPPER"

echo "E3V_F_STATIC_WRAPPER_ARTIFACT_SMOKE_OK"
