#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3v-e-option-b-wrapper-code-design-no-apply.md"

echo "=== Stage 16 E3V-E smoke: Option B wrapper code design, no apply ==="

test -s "$DOC"

grep -F "No Apply" "$DOC" || grep -F "no-apply" "$DOC"
grep -F "does not create the runtime wrapper yet" "$DOC"
grep -F "No DB write is performed" "$DOC"
grep -F "No job is claimed" "$DOC"
grep -F "ops/scheduler/stage-16-e3v-run-one-existing-status-atomic-claim-dispatch.sh" "$DOC"
grep -F "ops/smoke/check-stage-16-e3v-run-one-existing-status-atomic-claim-dispatch.sh" "$DOC"
grep -F -- "--dry-run" "$DOC"
grep -F -- "--execute-approved" "$DOC"
grep -F "APPROVE_STAGE_16_E3V_RUN_ONE_EXISTING_STATUS_ATOMIC_CLAIM_DISPATCH_ONLY" "$DOC"
grep -F "PVESO from Tailscale status" "$DOC"
grep -F "forbidden job ids" "$DOC"
grep -F "23" "$DOC"
grep -F "24" "$DOC"
grep -F "27" "$DOC"
grep -F "28" "$DOC"
grep -F "ELIGIBLE_WOULD_CLAIM_COUNT=1" "$DOC"
grep -F "qwen2.5:32b-instruct-q4_K_M" "$DOC"
grep -F "BEGIN IMMEDIATE" "$DOC"
grep -F "SET status='running'" "$DOC"
grep -F "changes() == 1" "$DOC"
grep -F "status=running" "$DOC"
grep -F "running -> failed" "$DOC"
grep -F "DO_NOT_RERUN" "$DOC"
grep -F "completed_with_one_result_do_not_rerun" "$DOC"
grep -F "running_zero_results_runner_active_do_not_rerun" "$DOC"
grep -F "non-localhost 11434 listener count is 0" "$DOC"
grep -F "CT101_STATUS=stopped" "$DOC"
grep -F "CT101_ONBOOT=0" "$DOC"
grep -F "atomic_claim_result.txt" "$DOC"
grep -F "completion_result.txt" "$DOC"
grep -F "E3V_OPTION_B_ATOMIC_CLAIM_ONE_SHOT_DISPATCH_OK" "$DOC"
grep -F "REFUSE_APPROVAL_MISSING" "$DOC"
grep -F "REFUSE_ATOMIC_CLAIM_NOT_ONE" "$DOC"
grep -F "no hardcoded pveso DNS dependency" "$DOC"
grep -F "It does not create the runtime wrapper" "$DOC"
grep -F "It does not call a model" "$DOC"

echo "E3V_E_OPTION_B_WRAPPER_CODE_DESIGN_NO_APPLY_SMOKE_OK"
