#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOC="$ROOT/docs/stage-17k-z-r2-companion-study-source-workflow-plan.md"

test -f "$DOC"

grep -Fq "Companion Study Source Workflow Plan" "$DOC"
grep -Fq "Companion should not create, edit, delete, import, export, or remove decks/cards." "$DOC"
grep -Fq "Study owns deck/card creation, editing, deletion" "$DOC"
grep -Fq "source-agnostic inventory interface" "$DOC"
grep -Fq "apc_local" "$DOC"
grep -Fq "anki_local_browser" "$DOC"
grep -Fq "google_drive_synced" "$DOC"
grep -Fq "future_external_source" "$DOC"
grep -Fq "source_type" "$DOC"
grep -Fq "deck_name" "$DOC"
grep -Fq "write_supported" "$DOC"
grep -Fq "all cards" "$DOC"
grep -Fq "easy cards" "$DOC"
grep -Fq "medium cards" "$DOC"
grep -Fq "hard cards" "$DOC"
grep -Fq "new cards" "$DOC"
grep -Fq "balanced" "$DOC"
grep -Fq "Idle / no active session" "$DOC"
grep -Fq "Running / started session" "$DOC"
grep -Fq "Paused session" "$DOC"
grep -Fq "Ended session" "$DOC"
grep -Fq "repeat question" "$DOC"
grep -Fq "flag card" "$DOC"
grep -Fq "skip card" "$DOC"
grep -Fq "tell me the answer" "$DOC"
grep -Fq "answer the question" "$DOC"
grep -Fq "runCompanionStudyWorkflow" "$DOC"
grep -Fq "Google Drive sync does not need to be fully working before defining Companion study workflow." "$DOC"
grep -Fq "Before implementing final end-session stat persistence" "$DOC"
grep -Fq "planning only" "$DOC"
grep -Fq "No source patch, frontend deploy, backend deploy, DB write" "$DOC"

echo "PASS: Stage 17K-Z-R2 Companion study source workflow plan smoke passed"
