#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-17k-r14h-record-save-action-controller-loaded-no-ui-no-write-proof.md"
OUT_DIR="docs/smoke/generated/stage-17k-r14h-record-save-action-controller-loaded-no-ui-no-write-proof"

test -f "$DOC"
test -d "$OUT_DIR"

grep -Fq "Record Save Action Controller Loaded No UI/Write Proof" "$DOC"
grep -Fq "Browser proof passed" "$DOC"
grep -Fq "PASS_R14G_SAVE_ACTION_CONTROLLER_LOADED_NO_UI_NO_WRITE" "$DOC"
grep -Fq "controllerLoadedByScript true" "$DOC"
grep -Fq "controllerWindowPresent true" "$DOC"
grep -Fq "APC_LOCAL_BACKUP_CURRENT_FILE_SAVE_ACTION_CONTROLLER_R14D_SOURCE_ONLY" "$DOC"
grep -Fq "hasStateFunction true" "$DOC"
grep -Fq "executorLoadedByScript true" "$DOC"
grep -Fq "executorWindowPresent true" "$DOC"
grep -Fq "savePlanPreviewStillVisible true" "$DOC"
grep -Fq "hasUnsafeButton false" "$DOC"
grep -Fq "mountStatus 200" "$DOC"
grep -Fq "panelStatus 200" "$DOC"
grep -Fq "mountReferencesController false" "$DOC"
grep -Fq "panelReferencesController false" "$DOC"
grep -Fq "stateEligibleForFutureEnablement true" "$DOC"
grep -Fq "stateCanShowFutureSaveButton true" "$DOC"
grep -Fq "stateCanWriteNow false" "$DOC"
grep -Fq "stateWritesEnabledNow false" "$DOC"
grep -Fq "stateExecutorCallAllowedNow false" "$DOC"
grep -Fq "stateExecutorCalled false" "$DOC"
grep -Fq "stateRemovedFieldCount 4" "$DOC"
grep -Fq "stateAfterLegacyFieldPaths []" "$DOC"
grep -Fq "Choose local backup folder" "$DOC"
grep -Fq "Download snapshot" "$DOC"
grep -Fq "Preview backup file" "$DOC"
grep -Fq "Open current backup file" "$DOC"
grep -Fq "No source mutation" "$DOC"
grep -Fq "No current-file save in live UI" "$DOC"
grep -Fq "No same-file write path in live UI" "$DOC"

echo "PASS stage-17k-r14h record save action controller loaded no ui no write proof smoke"
