#!/usr/bin/env bash
set -euo pipefail

DOC="docs/stage-16-e3v-k-fresh-eligible-job-insert-plan-no-apply.md"

echo "=== Stage 16 E3V-K smoke: fresh eligible job insert plan, no apply ==="

test -s "$DOC"

grep -F "No Apply" "$DOC" || grep -F "no-apply plan" "$DOC"
grep -F "does not insert the job" "$DOC"
grep -F "does not write the DB" "$DOC"
grep -F "does not execute the wrapper" "$DOC"
grep -F "does not call a model" "$DOC"
grep -F "HEAD/origin/main: c8bd88d" "$DOC"
grep -F "E3V_DRY_RUN_RESULT=NO_ELIGIBLE_JOB_NO_RUNTIME" "$DOC"
grep -F "E3V_DRY_RUN_ELIGIBLE_JOB_COUNT=0" "$DOC"
grep -F "APPROVE_STAGE_16_E3V_L_INSERT_ONE_FRESH_ELIGIBLE_OPTION_B_JOB_ONLY" "$DOC"
grep -F "status=queued" "$DOC"
grep -F "attempts=0" "$DOC"
grep -F "requested_model=qwen2.5:32b-instruct-q4_K_M" "$DOC"
grep -F "job_type=stage16_e3v_option_b_atomic_claim_fresh_model_smoke" "$DOC"
grep -F "job_results_for_fresh_job=0" "$DOC"
grep -F "23" "$DOC"
grep -F "24" "$DOC"
grep -F "27" "$DOC"
grep -F "28" "$DOC"
grep -F "BEGIN IMMEDIATE" "$DOC"
grep -F "INSERT INTO jobs" "$DOC"
grep -F "SELECT last_insert_rowid" "$DOC"
grep -F "E3V_L_INSERTED_FRESH_JOB_ID=<id>" "$DOC"
grep -F "E3V_L_ELIGIBLE_JOB_COUNT_AFTER=1" "$DOC"
grep -F "E3V_L_INSERT_ONE_FRESH_ELIGIBLE_JOB_OK" "$DOC"
grep -F "REFUSE_APPROVAL_MISSING" "$DOC"
grep -F "REFUSE_EXISTING_ELIGIBLE_JOB_PRESENT" "$DOC"
grep -F "REFUSE_INSERT_NOT_EXACTLY_ONE" "$DOC"
grep -F "REFUSE_INSERTED_JOB_HAS_RESULT" "$DOC"
grep -F "REFUSE_FORBIDDEN_JOB_ID" "$DOC"
grep -F "E3V_DRY_RUN_RESULT=WOULD_CLAIM_ONE_JOB_NO_RUNTIME" "$DOC"
grep -F "WOULD_ATOMIC_CLAIM job_id=<fresh_job_id>" "$DOC"
grep -F "Runtime remains blocked" "$DOC"
grep -F "No atomic claim dispatch is approved" "$DOC"

echo "E3V_K_FRESH_ELIGIBLE_JOB_INSERT_PLAN_NO_APPLY_SMOKE_OK"
