#!/usr/bin/env bash
set -euo pipefail

mode="${1:-}"
case "$mode" in
  --dry-run|--run) ;;
  *)
    echo "usage: $0 --dry-run|--run"
    exit 2
    ;;
esac

WRAPPER="${E3Y_TIMEOUT_SAFE_WRAPPER:-ops/scheduler/stage-16-e3w-timeout-safe-one-job-dispatch.sh}"
DB="${E3Y_CT203_DB:-/var/lib/edge-queue-controller/edge_queue.sqlite3}"

EXPECTED_JOB_ID="${E3Y_EXPECTED_JOB_ID:-}"
EXPECTED_MODEL="${E3Y_EXPECTED_MODEL:-qwen2.5:0.5b}"
EXPECTED_JOB_TYPE="${E3Y_EXPECTED_JOB_TYPE:-stage16_e3y_scheduler_one_shot_small_model_completion_smoke}"

MODEL_TIMEOUT_SECONDS="${E3Y_MODEL_TIMEOUT_SECONDS:-45}"
WRAPPER_TOTAL_SECONDS="${E3Y_WRAPPER_TOTAL_SECONDS:-120}"
NUM_PREDICT="${E3Y_NUM_PREDICT:-8}"
TEMPERATURE="${E3Y_TEMPERATURE:-0}"

E3Y_DEFAULT_REQUIRED_APPROVAL="APPROVE_STAGE_16_E3Y_F_RUN_ONE_SHOT_SCHEDULER_SMALL_MODEL_JOB_ONLY"
E3Y_REQUIRED_APPROVAL="${E3Y_REQUIRED_APPROVAL:-$E3Y_DEFAULT_REQUIRED_APPROVAL}"
E3Y_APPROVAL="${E3Y_APPROVAL:-}"

# Internal wrapper approval is separate. The scheduler checks the E3Y approval first,
# then delegates to the proven E3W/E3X timeout-safe wrapper approval shim.
E3W_INTERNAL_REQUIRED_APPROVAL="APPROVE_STAGE_16_E3X_E_RUN_ONE_SMALL_MODEL_TIMEOUT_SAFE_JOB_ONLY"

echo "=== Stage 16 E3Y one-shot scheduler dispatch ==="
echo "MODE=$mode"
echo "EXPECTED_JOB_ID=${EXPECTED_JOB_ID:-<unset>}"
echo "EXPECTED_MODEL=$EXPECTED_MODEL"
echo "EXPECTED_JOB_TYPE=$EXPECTED_JOB_TYPE"
echo "MODEL_TIMEOUT_SECONDS=$MODEL_TIMEOUT_SECONDS"
echo "WRAPPER_TOTAL_SECONDS=$WRAPPER_TOTAL_SECONDS"
echo "NUM_PREDICT=$NUM_PREDICT"
echo "TEMPERATURE=$TEMPERATURE"
echo "NO_PERSISTENT_SCHEDULER_ACTIVATION"
echo "NO_PERSISTENT_WORKER_ACTIVATION"
echo "DO_NOT_RERUN_E3V_Q"
echo "DO_NOT_RETRY_JOB_29"
echo "DO_NOT_RERUN_JOB_30"
echo "DO_NOT_RERUN_JOB_31"

if [ -z "$EXPECTED_JOB_ID" ]; then
  echo "REFUSE_E3Y_ONE_SHOT_SCHEDULER: E3Y_EXPECTED_JOB_ID required"
  exit 2
fi

case "$EXPECTED_JOB_ID" in
  29|30|31)
    echo "REFUSE_E3Y_ONE_SHOT_SCHEDULER: forbidden historical job id"
    exit 2
    ;;
esac

if [ ! -x "$WRAPPER" ]; then
  echo "REFUSE_E3Y_ONE_SHOT_SCHEDULER: timeout-safe wrapper missing or not executable"
  exit 2
fi

dirty="$(git status --short)"
if [ -n "$dirty" ]; then
  echo "REFUSE_E3Y_ONE_SHOT_SCHEDULER: repo dirty"
  printf '%s\n' "$dirty"
  exit 2
fi

if [ "$mode" = "--dry-run" ]; then
  echo "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_ONLY"
  E3W_EXPECTED_JOB_ID="$EXPECTED_JOB_ID" \
  E3W_EXPECTED_MODEL="$EXPECTED_MODEL" \
  E3W_EXPECTED_JOB_TYPE="$EXPECTED_JOB_TYPE" \
  E3W_MODEL_TIMEOUT_SECONDS="$MODEL_TIMEOUT_SECONDS" \
  E3W_WRAPPER_TOTAL_SECONDS="$WRAPPER_TOTAL_SECONDS" \
  E3W_NUM_PREDICT="$NUM_PREDICT" \
  E3W_TEMPERATURE="$TEMPERATURE" \
  E3W_CT203_DB="$DB" \
  "$WRAPPER" --dry-run
  echo "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_WOULD_SELECT_JOB id=$EXPECTED_JOB_ID model=$EXPECTED_MODEL job_type=$EXPECTED_JOB_TYPE"
  echo "E3Y_ONE_SHOT_SCHEDULER_DRY_RUN_NO_DB_WRITE_NO_MODEL_CALL"
  exit 0
fi

echo "E3Y_ONE_SHOT_SCHEDULER_RUN_MODE_APPROVAL_REQUIRED=$E3Y_REQUIRED_APPROVAL"
if [ "$E3Y_APPROVAL" != "$E3Y_REQUIRED_APPROVAL" ]; then
  echo "REFUSE_E3Y_ONE_SHOT_SCHEDULER: runtime approval missing or wrong"
  exit 2
fi

echo "E3Y_ONE_SHOT_SCHEDULER_APPROVAL_ACCEPTED=true"
echo "E3Y_ONE_SHOT_SCHEDULER_DELEGATING_TO_TIMEOUT_SAFE_WRAPPER=true"

E3W_REQUIRED_APPROVAL="$E3W_INTERNAL_REQUIRED_APPROVAL" \
E3W_APPROVAL="$E3W_INTERNAL_REQUIRED_APPROVAL" \
E3W_EXPECTED_JOB_ID="$EXPECTED_JOB_ID" \
E3W_EXPECTED_MODEL="$EXPECTED_MODEL" \
E3W_EXPECTED_JOB_TYPE="$EXPECTED_JOB_TYPE" \
E3W_MODEL_TIMEOUT_SECONDS="$MODEL_TIMEOUT_SECONDS" \
E3W_WRAPPER_TOTAL_SECONDS="$WRAPPER_TOTAL_SECONDS" \
E3W_NUM_PREDICT="$NUM_PREDICT" \
E3W_TEMPERATURE="$TEMPERATURE" \
E3W_CT203_DB="$DB" \
"$WRAPPER" --run

echo "E3Y_ONE_SHOT_SCHEDULER_RUNTIME_DELEGATION_DONE"
